:cards:
  fr:
  - :name: Alimentation, marchés & produits locaux
    :photo: https://github.com/thomas6791/photos-pays/blob/master/marche-reicho.jpeg?raw=true
    :description: Trouver les commerces d'alimentation, boulangeries, supermarchés, marchés et produits du terroir aux alentours
    :link: /fr/alimentation
  - :name: Chemin des châteaux forts d'Alsace
    :photo: #wegelnburg.jpg
    :description: fé"rngn"iégni" jgn"knrklanzlkgn ngjzng
    :link:
  - :name: Visiter Strasbourg
    :photo: #strasbourg.jpg
    :description: bonjour
    :link:
  - :name: Le château du Schoeneck
    :photo: schoeneck.jpg
    :description: ozfregergze
    :link:
  - :name: La Ligne Maginot d'Alsace
    :photo: casemate_neunhoffen.jpg
    :description: casemate neunhoffen
    :link: /fr/ligne-maginot-alsace
  - :name: Marchés de Noël en Alsace
    :photo: https://github.com/thomas6791/photos-pays/blob/master/marche%CC%81_noel-min.jpg?raw=true
    :description: Les marchés de Noël en Alsace du Nord et dans le reste de la région
    :link: /marches-noel
  - :name: Parcs d'attractions & aquatiques
    :photo: https://github.com/thomas6791/photos-pays/blob/master/europapark.jpg?raw=true
    :description: Les parcs d'attractions et aquatiques dans et proche de la région
    :link: /parcs-attractions

  en:
  - :name: Chemin des châteaux forts d'Alsace
    :photo: #wegelnburg.jpg
    :description: fé"rngn"iégni" jgn"knrklanzlkgn ngjzng
  - :name: Visit Strasbourg
    :photo: #strasbourg.jpg
    :description: bonjour
  - :name: Schoeneck Castle
    :photo: schoeneck.jpg
    :description: ozfregergze
  - :name: La Ligne Maginot d'Alsace
    :photo: casemate_neunhoffen.jpg
    :description: casemate neunhoffen
  de:
  - :name: Allemand forts d'Alsace
    :photo: #wegelnburg.jpg
    :description: fé"rngn"iégni" jgn"knrklanzlkgn ngjzng
  - :name: Visit Strasbourg
    :photo: #strasbourg.jpg
    :description: bonjour
  - :name: Schoeneck Castle
    :photo: schoeneck.jpg
    :description: ozfregergze
  - :name: La Ligne Maginot d'Alsace
    :photo: casemate_neunhoffen.jpg
    :description: casemate neunhoffen
:heidelbeere:
  fr:
  - :name: Appartement de 100m2
    :photo: heidelbeere/chambre-bleue.jpg
    :description: Appartement tout équipé pouvant accueillir 4 personnes. A partir de 70€/nuit
    :link: meuble_heidelbeere_holidayrentings_path
  - :name: Studio Meublé
    :photo: heidelbeere/chambre grise.jpg
    :description: Studio avec une capacité de 3 personnes. A partir de 70€/nuit
    :link: studio_heidelbeere_holidayrentings_path
  en:
  - :name: Appartement de 100m<sup>2<sup>
    :photo: heidelbeere/chambre-bleue.jpg
    :description: Appartement tout équipé pouvant accueillir 4 personnes. A partir de 70€/nuit
  - :name: Studio Meublé
    :photo: heidelbeere/chambre grise.jpg
    :description: Studio avec une capacité de 3 personnes. A partir de 70€/nuit
  de:
  - :name: Appartement de 100m<sup>2<sup>
    :photo: heidelbeere/chambre-bleue.jpg
    :description: Appartement tout équipé pouvant accueillir 4 personnes. A partir de 70€/nuit
  - :name: Studio Meublé
    :photo: heidelbeere/chambre grise.jpg
    :description: Studio avec une capacité de 3 personnes. A partir de 70€/nuit
