:cards:
  fr:
  - :name: Chemin des châteaux forts d'Alsace
    :photo: wegelnburg.jpg
    :description: fé"rngn"iégni" jgn"knrklanzlkgn ngjzng
  - :name: Visiter Strasbourg
    :photo: strasbourg.jpg
    :description: bonjour
  - :name: Le château du Schoeneck
    :photo: schoeneck.jpg
    :description: ozfregergze
  en:
  - :name: Chemin des châteaux forts d'Alsace
    :photo: wegelnburg.jpg
    :description: fé"rngn"iégni" jgn"knrklanzlkgn ngjzng
  - :name: Visit Strasbourg
    :photo: strasbourg.jpg
    :description: bonjour
  - :name: Schoeneck Castle
    :photo: schoeneck.jpg
    :description: ozfregergze
  de:
  - :name: Allemand forts d'Alsace
    :photo: wegelnburg.jpg
    :description: fé"rngn"iégni" jgn"knrklanzlkgn ngjzng
  - :name: Visit Strasbourg
    :photo: strasbourg.jpg
    :description: bonjour
  - :name: Schoeneck Castle
    :photo: schoeneck.jpg
    :description: ozfregergze
:heidelbeere:
  fr:
  - :name: Appartement de 100m2
    :photo: heidelbeere/chambre-bleue.jpg
    :description: Appartement tout équipé pouvant accueillir 4 personnes. A partir de 70€/nuit
    :link: meuble_heidelbeere_holidayrentings_path
  - :name: Studio Meublé
    :photo: heidelbeere/chambre grise.jpg
    :description: Studio avec une capacité de 3 personnes. A partir de 70€/nuit
    :link: studio_heidelbeere_holidayrentings_path
  en:
  - :name: Appartement de 100m<sup>2<sup>
    :photo: heidelbeere/chambre-bleue.jpg
    :description: Appartement tout équipé pouvant accueillir 4 personnes. A partir de 70€/nuit
  - :name: Studio Meublé
    :photo: heidelbeere/chambre grise.jpg
    :description: Studio avec une capacité de 3 personnes. A partir de 70€/nuit
  de:
  - :name: Appartement de 100m<sup>2<sup>
    :photo: heidelbeere/chambre-bleue.jpg
    :description: Appartement tout équipé pouvant accueillir 4 personnes. A partir de 70€/nuit
  - :name: Studio Meublé
    :photo: heidelbeere/chambre grise.jpg
    :description: Studio avec une capacité de 3 personnes. A partir de 70€/nuit
