:lieux:
  fr:
  - :name: Le château du Wegelnburg
    :photo: top/wegelnburg.png
    :summary: Trouver les commerces d'alimentation, boulangeries, supermarchés, marchés et produits du terroir aux alentours
    :location: français
    :tips: ddd
    :link: aaa
  - :name: Altschlossfelssen
    :photo: top/altschlosfelssen.png
    :summary: alll
    :location: français
    :tips: fr
    :link: fr-rr

  en:
  - :name: Le château du Wegelnburg
    :photo: top/wegelnburg.png
    :summary: Trouver les commerces d'alimentation, boulangeries, supermarchés, marchés et produits du terroir aux alentours
    :location: français
    :tips: ddd
    :link: aaa
  - :name: Altschlossfelssen
    :photo: top/altschlosfelssen.png
    :summary: alll
    :location: français
    :tips: en
    :link: en-rr
  de:
  - :name: Le château du Wegelnburg
    :photo: top/wegelnburg.png
    :summary: Trouver les commerces d'alimentation, boulangeries, supermarchés, marchés et produits du terroir aux alentours
    :location: français
    :tips: ddd
    :link: aaa
  - :name: Altschlossfelssen
    :photo: top/altschlosfelssen.png
    :summary: alll
    :location: français
    :tips: de
    :link: de-rr
