:lieux:
  fr:
  - :name: Le château du Wegelnburg
    :photo: top/wegelnburg.png
    :summary: Faisant parti de la randonnée des 4 châteaux près du Fleckenstein, le château du Wegelnburg peut offrir pour ceux se levant aux aurores un panorama spectaculaire sur la palatinat et les vosges du nord.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3207.46795381889!2d7.784158125974268!3d49.06158194859821!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968bab3bca9be9%3A0xf1ac0dd783cca5b7!2sWegelnburg!5e0!3m2!1sfr!2sfr!4v1628915453733!5m2!1sfr!2sfr"
    :tips: Pour voir une mer de nuage, il faudra se lever aux aurores, monter pendant 30-40min jusqu'au château pour ensuite voir ce spectacle. Des précipitations la veille ou lors de l'Automne, saison plus humidue, peut également être une bonne période pour ce spectacle.
    :link: aaa
    :loc_summary: Fleckenstein, Lembach, 67510, Alsace
  - :name: Altschlossfelssen
    :photo: top/altschlossfelssen.png
    :summary: Surnommé le Colorado Lorrain, le rocher du Altschlossfelssen est une des plus grandes barres rocheuses en grès des vosges de la Palatinat offrant un superbe spectacle géologique.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41808.35864483865!2d7.484754848324172!3d49.086214340540174!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479680b0a85d2005%3A0xfeb002a9e55bf931!2sAltschlossfelsen!5e0!3m2!1sfr!2sfr!4v1628916165031!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Roppeviller, 57230, Lorraine
  - :name: Chemin des cimes
    :photo: https://www.chemindescimes-alsace.fr/bwp-wAssets/img/elsass/Pfad-und-Turm-vor-Eroeffnung/DSC00256.JPG
    :summary: Long d'un kilomètre de long et d'une hauteur de 30m, le "chemin des cimes", structure unique en France vous donnera une vue dégagée sur les Vosges du Nord. On y apercevra également par temps clair la Forêt Noire, les Vosges et parfois même la cathédrale de Strasbourg.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2617.598754940427!2d7.854935751259339!3d48.99919279863479!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796f386f61aa06d%3A0xcad41ad12cd0fdba!2sChemin%20des%20Cimes%20Alsace!5e0!3m2!1sfr!2sfr!4v1628916309860!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Drachenbronn-Birlenbach, 67160, Alsace
  - :name: Le Fleckenstein
    :photo: https://img2.oastatic.com/img2/57231788/max/fleckenstein-luftaufnahme.jpg
    :summary: Château situé sur un piton rocheux, le château du Fleckenstein est le château le plus visité d'Alsace du Nord et le second derrière le château du Haut-Koenigsbourg. La visite de ce château peut s'accompagner de la visite de 3 autres pour une randonnée d'environ 2h.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2615.1983704999366!2d7.769759851260731!3d49.04485169541199!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968bbd1a749c6b%3A0x3f77e58e15189a07!2sCh%C3%A2teau%20fort%20de%20Fleckenstein!5e0!3m2!1sfr!2sfr!4v1628916383360!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Fleckenstein, Lembach, 67510, Alsace
  - :name: Le château du Falkenstein
    :photo: https://www.chateauxfortsalsace.com/wp-content/uploads/2019/02/R.Falkenstein-vue-a%C3%A9rienne-CCPB-002.jpg
    :summary: Autre château emblématique des Vosges du Nord, le château troglodyte du Falkenstein vous donnera l'opportunité de découvrir les nombreux aspects de ce type de château et un panorama sur les Vosges du Nord.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2617.2953164184487!2d7.563222751259507!3d49.00496639822733!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968451cc403701%3A0x204dc2b9e998914e!2sCh%C3%A2teau%20du%20Falkenstein!5e0!3m2!1sfr!2sfr!4v1628916432201!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Falkenstein, Philippsbourg, 57230, Lorraine
  - :name: Le Fort de Schoenenbourg
    :photo: https://media-cdn.tripadvisor.com/media/photo-s/10/fe/5e/30/entree-munitions.jpg
    :summary: ///
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2619.316305487036!2d7.91017775125837!3d48.96650300094065!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796f1bf00624c01%3A0xcb5ab755b3c7be65!2sLigne%20Maginot%20Fort%20Schoenenbourg!5e0!3m2!1sfr!2sfr!4v1628916475444!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Hunspach, 67250, Alsace
  - :name: Hunspach
    :photo: https://www.visit.alsace/wp-content/uploads/2019/02/village-hunspach-karl-heinz-haenel-1600x900.jpg
    :summary: Faisant parti des "plus beaux villages de France", le village de Hunspach a également été élu "villge préféré des français 2020". Une des particularités de ce village est l'homogénéité de ses maisons à colombage blanches.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d20958.109733640158!2d7.912265011241675!3d48.95798484743765!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796f19106791d89%3A0x40a5fb99a395570!2s67250%20Hunspach!5e0!3m2!1sfr!2sfr!4v1628916519168!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Hunspach, 67250, Alsace
  - :name: La Tour du Grand Wintersberg
    :photo: http://apps.tourisme-alsace.info/photos/niederbronn/photos/tour-wintersberg-1.JPG
    :summary: A 581 mètres de hauteur, la tour du Grand Wintersberg est le point culminant du massif des Vosges du Nord. l'accès à la Tour du Wintersberg se fait par divers moyens. A son sommet, un panorama vous est offert sur toute l'étendue des Vosges du Nord.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2618.6765571365804!2d7.612177951258706!3d48.978681100081815!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968563b51b4faf%3A0x9ff306cb895fbf02!2sTour%20panoramique%20du%20Grand%20Wintersberg!5e0!3m2!1sfr!2sfr!4v1628916585396!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Niederbronn-les-Bains, 67110, Alsace
  - :name: La ville de Wissembourg
    :photo: https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/56/d0/75/just-around-the-corner.jpg?w=500&h=300&s=1
    :summary: alll
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83730.61890618093!2d7.892747650549754!3d49.018539882670744!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796f69b021c45e5%3A0xc4bed6635a742ef5!2s67160%20Wissembourg!5e0!3m2!1sfr!2sfr!4v1628916626316!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Wissembourg, 67160, Alsace
  - :name: Le château du Wasigenstein
    :photo: https://www.visit.alsace/wp-content/uploads/lei/pictures/219006244-chateau-de-wasigenstein-1-1600x900.jpg
    :summary: alll
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2614.9636494441474!2d7.706180951260867!3d49.04931474509687!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968917d3215103%3A0x3183f6cc9270a91b!2sCh%C3%A2teau%20du%20Wasigenstein!5e0!3m2!1sfr!2sfr!4v1628916676764!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Obersteinbach, 67510, Alsace
  - :name: Le château du Schoeneck
    :photo: top/schoeneck.png
    :summary: Château souvent moins connu que les autres, le château du Schoeneck est pourtant un des plus beaux des Vosges du Nord. Une association travaille activement à sa restauration. Par beau temps, son sommet offre une superbe vue.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2616.5776134740136!2d7.656237851259952!3d49.01862029726374!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968f39950e39e7%3A0x7bbc0187e93d7416!2zQ2jDonRlYXUgZGUgU2NoxZNuZWNr!5e0!3m2!1sfr!2sfr!4v1628916733030!5m2!1sfr!2sfr"
    :tips: fr
    :link: fr-rr
    :loc_summary: Dambach, 67110, Alsace

  en:
  - :name: Wegelnburg Castle
    :photo: top/wegelnburg.png
    :summary: As part of the 4 castles hike near Fleckenstein, the Wegelnburg castle can offer a spectacular panorama of the Palatinate and the northern Vosges for the most motivated early risers.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3207.46795381889!2d7.784158125974268!3d49.06158194859821!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968bab3bca9be9%3A0xf1ac0dd783cca5b7!2sWegelnburg!5e0!3m2!1sfr!2sfr!4v1628915453733!5m2!1sfr!2sfr"
    :tips: To see a sea of clouds, you will have to get up at dawn, climb for 30-40min to the castle and then see the show. Rainfall the day before or in the wetter Autumn season can also be a good time to see this show.
    :link: aaa
    :loc_summary: Lembach, Fleckenstein, 67510, Alsace
  - :name: Altschlossfelssen
    :photo: top/altschlosfelssen.png
    :summary: alll
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41808.35864483865!2d7.484754848324172!3d49.086214340540174!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479680b0a85d2005%3A0xfeb002a9e55bf931!2sAltschlossfelsen!5e0!3m2!1sfr!2sfr!4v1628916165031!5m2!1sfr!2sfr"
    :tips: en
    :link: en-rr
    :loc_summary: Lembach, Fleckenstein, 67510, Alsace
  de:
  - :name: Burg Wegelnburg
    :photo: top/wegelnburg.png
    :summary: Als Teil der 4-Burgen-Wanderung bei Fleckenstein bietet die Wegelnburg für besonders motivierte Aufsteher in der Morgendämmerung ein spektakuläres Panorama auf die Pfalz und die Nordvogesen.
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3207.46795381889!2d7.784158125974268!3d49.06158194859821!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47968bab3bca9be9%3A0xf1ac0dd783cca5b7!2sWegelnburg!5e0!3m2!1sfr!2sfr!4v1628915453733!5m2!1sfr!2sfr"
    :tips: Um ein Wolkenmeer zu sehen, muss man im Morgengrauen aufstehen, 30-40 Minuten zur Burg hinaufsteigen und dann das Schauspiel sehen. Auch Regenfälle am Vortag oder in der feuchteren Herbstzeit können ein guter Zeitpunkt sein, um dieses Schauspiel zu sehen.
    :link: aaa
    :loc_summary: Lembach, Fleckenstein, 67510, Alsace
  - :name: Altschlossfelssen
    :photo: top/altschlosfelssen.png
    :summary: alll
    :location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41808.35864483865!2d7.484754848324172!3d49.086214340540174!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479680b0a85d2005%3A0xfeb002a9e55bf931!2sAltschlossfelsen!5e0!3m2!1sfr!2sfr!4v1628916165031!5m2!1sfr!2sfr"
    :tips: de
    :link: de-rr
    :loc_summary: Lembach, Fleckenstein, 67510, Alsace
