:taxes:
  niederbronn:
    :palace: 3.00
    :five: 2.20
    :four: 1.80
    :three: 1.25
    :two: 0.99
    :one: 0.80
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.36
    :camping-1-2: 0.20
    :add_tax?: oui
    :add_tax: 1.10
    :plafond:
  kaysersberg:
    :palace: 3.30
    :five: 1.65
    :four: 1.10
    :three: 1.00
    :two: 0.90
    :one: 0.80
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.45
    :camping-1-2: 0.20
    :add_tax?: oui
    :add_tax: 1.10
    :plafond:
  obernai:
    :palace: 3.30
    :five: 1.50
    :four: 1.50
    :three: 1.10
    :two: 0.90
    :one: 0.80
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.50
    :camping-1-2: 0.22
    :add_tax?: oui
    :add_tax: 1.10
    :plafond: 2.30
