:taxes:
  niederbronn:
  - :palace: 3.00
  - :5: 2.20
  - :4: 1.80
  - :3: 1.25
  - :2: 0.99
  - :1: 0.80
  - :nc-hotel: 0.55
  - :nc-meuble: 0.55
  - :camping-3-4-5: 0.36
  - :camping-1-2: 0.20
  - :add_tax?: oui
  - :add_tax: 1.10
