# Ajout des taxes de séjour en intégrant la taxe additionnelle departementale de +10%
:taxes:
  niederbronn:
    :palace: 3.00
    :five: 2.20
    :four: 1.80
    :three: 1.25
    :two: 0.99
    :one: 0.80
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.36
    :camping-1-2: 0.20
    :add_tax?: oui
    :add_tax: 1.10
    :plafond:
    :taux: 0.05
  morsbronn:
    :palace: 2.00
    :five: 1.20
    :four: 1.00
    :three: 0.80
    :two: 0.70
    :one: 0.70
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.55
    :camping-1-2: 0.22
    :add_tax?: oui
    :add_tax: 1.10
    :plafond:
    :taux: 0.05
  wissembourg:
    :palace: 4.40
    :five: 1.65
    :four: 1.50
    :three: 1.10
    :two: 0.90
    :one: 0.70
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.50
    :camping-1-2: 0.22
    :add_tax?: oui
    :add_tax: 1.10
    :plafond:
    :taux: 0.05
  kaysersberg:
    :palace: 3.30
    :five: 1.65
    :four: 1.10
    :three: 1.00
    :two: 0.90
    :one: 0.80
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.45
    :camping-1-2: 0.20
    :add_tax?: oui
    :add_tax: 1.10
    :plafond:
    :taux: 0.05
  obernai:
    :palace: 3.30
    :five: 1.50
    :four: 1.50
    :three: 1.10
    :two: 0.90
    :one: 0.80
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.50
    :camping-1-2: 0.22
    :add_tax?: oui
    :add_tax: 1.10
    :plafond: 2.30
    :taux: 0.05
  colmar:
    :palace: 4.40
    :five: 1.65
    :four: 1.25
    :three: 1.10
    :two: 0.85
    :one: 0.60
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.60
    :camping-1-2: 0.22
    :add_tax?: oui
    :add_tax: 1.10
    :plafond: 2.30
    :taux: 0.05
  strasbourg:
    :palace: 4.40
    :five: 3.30
    :four: 2.45
    :three: 1.65
    :two: 0.80
    :one: 0.55
    :nc-hotel: 0.5
    :nc-meuble: 0.5
    :camping-3-4-5: 0.55
    :camping-1-2: 0.22
    :add_tax?: oui
    :add_tax: 1.10
    :plafond: 2.30
    :taux: 0.04
